### ISSUE TITLE
Input text files for spin-polarised calculations

### ISSUE THREAD

**Issue by keeeto** [SMTG-UCL/galore#18]
**Is your feature request related to a problem? Please describe.**

The output of spin-polarised DOS from `sumo` doesn't play nicely with the `galore` lookup for cross-sections.

Example, the `O_dos` file :
[O_dos.dat.gz](https://github.com/SMTG-UCL/galore/files/2173507/O_dos.dat.gz)

If I run `galore  O_dos.dat --plot --pdos  --weighting alka`

I get `Could not find cross-section data for element O, orbital sup. Skipping this orbital.`

**Describe the solution you'd like**

I would like a solution whereby `galore` would seamlessly take spin-polarised output from `sumo` as input. In the way that it can read the `vasprun.xml`. 

**Describe alternatives you've considered**

I can alter the header of the `sumo` generated file, but this raises some other  probems. E.g. if I change the header to: ` # energy s s p p d d`

The code runs and plots, but I do get the following output, which seems like something has gone wrong:

```
  Orbital cross-section weights per electron:
   O s: 9.500e-04
Could not find cross-section data for element O, orbital s_1. Skipping this orbital.
   O p: 6.000e-05
Could not find cross-section data for element O, orbital p_1. Skipping this orbital.
Could not find cross-section data for element O, orbital d_1. Skipping this orbital.
```

**Additional context**

n/a

**Comment by ajjackson** [comment]
We should sort this out to be compatible with Sumo output, either by tweaking Galore or both Galore and Sumo.

**Comment by ajjackson** [comment]
I've pushed something to master which _should_ fix this. Can you give it a try before I make an official release?

**Comment by cnsavory** [comment]
@ajjackson , sorry, I gave this fix a try as this issue was causing problems when trying to load sumo's Questaal output. It doesn't seem to be working for me, when I checked on a VASP equivalent where I have both vasprun and the sumo-dosplot output files - I just get a galore output that is 0 for most of the energy range when loading from the sumo output files (checked vs both total dos and individual pdos). Loading from straight from the vasprun.xml instead works fine. Is this possibly because the sumo outputs give the spin down component as negative values and the spin up as positive?

**Comment by ajjackson** [comment]
That's hilarious, I had no idea dosplot worked like that. Should be able to fix with a well-placed `abs(x)`.

**Comment by ajjackson** [comment]
Ok, I've pushed a fix to master!

**Comment by ajjackson** [comment]
Have received work from @cnsavory that this is working, closing for now.
